comp:
	gcc main.c functions.c functions.h -o 4uzd.exe
run: 
	4uzd.exe
comprun:
	gcc main.c functions.c functions.h -o 4uzd.exe
	4uzd.exe
test:
	gcc test.c functions.c functions.h -o test.exe
	test.exe